import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserStoreProvider } from "@/store/UserStore";
import { CssVarsProvider } from "@mui/joy/styles";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hotel Opulence",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserStoreProvider>
      <CssVarsProvider defaultMode="dark">
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </CssVarsProvider>
    </UserStoreProvider>
  );
}
